

export const UCD_Expenses_Info = [
    {
        Title: "Medical Center",
        Details: "The cost of providing care at the Medical Center is roughly what we get paid to provide it."
    },
    {
        Title: "Teaching and Teaching Support" ,
        Details: "Professors, advisors, deans, the library, the computer labs, etc, including Medical School faculty salaries."
    },
    {
        Title: "Research",
        Details: "The costs of doing the research, mostly researcher salaries."
    },
    {
        Title: "Student Services and Financial Aid",
        Details: "Student Health, things covered by fees, Admissions, and also financial aid from the general funds, which is about $100M or 1.5%."
    },
    {
        Title: "Operations and Maintenance",
        Details: "Upkeep of the grounds and building, and utilities, which are less than 1%."
    },
    {
        Title: "Administration",
        Details: "Provost and Chancellor \'s offices, raising money, accounting, personnel, legal, making budgets."
    },
    {
        Title: "Services",
        Details: "The costs of providing dorms, dining,parking, etc."
    },
    {
        Title: "Public Service",
        Details: "Mostly the cooperative extension, which provides agricultural services to farmers, ranchers, winemakers, etc.  Part of our mission as a land grant university."
    },
    {
        Title: "Depreciation, Interest, etc.",
        Details: "Depreciation is the loss of value of buildings and equipment as they wear out. Mostly unavoidable financial losses."
    }
]

export const UCD_Revenues_Info = [
    {
        Title: "Medical Center",
        Details: "A large, not-for-profit regional medical center, including multiple hospitals, labs and clinics. Income comes from patients, medical insurance companies, and government programs like medicare.",
        Color: "#f0bf00"
    },
    {
        Title: "Student Fees",
        Details: "Fees are dedicated to specific services, such as athletic facilities, bus service (UNITRANS), student organizations, the CoHo and Student Community Center, etc.",
        Color: "#f6e50e"
    },{
        Title: "State of California",
        Details: "General funds given by the taxpayers of California, appropriated annualy by the state legislature. General funds are not dedicated to specific services.",
        Color: "#fff688"
    },{
        Title: "Tuition",
        Details: "Students pay tuition to attend the University. Non-California residents pay about twice as much as residents.  Tuition is also general funds.",
        Color: "#5f63ec"
    },{
        Title: "Research Grants",
        Details: "Government and industry funds given to faculty and graduate students to perform research projects. These include up to 50% overhead in addition to the cost of the research.",
        Color: "#71a8ff"
    },{
        Title: "Pell Grants",
        Details: "Federal grants for tuition and living expenses for low-income students. Percentage of students with Pell grants is a good way to measure who a University serves; at UCD, it\'s 34%; at Cal Tech it\'s 14%; At Sac State it\'s 71%.",
        Color: "#0f7ab4"
    },{
        Title: "Non-Educational",
        Details: "Services other than education that people pay for, like dorms, dining, parking, etc.  At UC Davis, this also includes almost $500M of revenue generated by medical school faculty, or 8%, making this category look really big.",
        Color: "#d4e4ff"
    },{
        Title: "Gifts and Endowments",
        Details: "Endowments are past gifts that were invested to provide income; interest is earned on other savings. The Museum is the direct result of a $10M gift from Jan Shrem and Maria Manetti Shrem.",
        Color: "#e3a400"
    }
]

